### ISSUE TITLE
bash format.bashのエラー

### ISSUE THREAD

**Issue by kaitokuroda** [infra-club-fmlorg/qemu-scripts#1]
linux環境

$ bash format.bash
bash: format.bash: そのようなファイルやディレクトリはありません

$ cd linux/
bash: cd: linux/: そのようなファイルやディレクトリはありません

$ bash install.bash
bash: install.bash: そのようなファイルやディレクトリはありません

このようなエラーが起きました。

**Comment by totto2727** [comment]
`pwd`で現在のパスを教えてもらえると助かります。

多分、リポジトリのディレクトリに入ってないことが原因だと思う

**Comment by fmlorg** [comment]
原則論の

　ls して
　存在を確認して
　./コマンド

実行するくせをつけてください。

そういう動作をしないOSがあるけど、てか、窓って名前のやつだけど、どっちの実装がいいの？と言われると微妙なところ。でも、サーバ機はUnixだから、Unixに慣れるべき

**Comment by kaitokuroda** [comment]
fukamatiken@fukamatiken-FMVA53A3W:$ pwd
/home/fukamatiken
fukamatiken@fukamatiken-FMVA53A3W:$ cd ..
fukamatiken@fukamatiken-FMVA53A3W:/home$ bash install.bash
bash: install.bash: そのようなファイルやディレクトリはありません
fukamatiken@fukamatiken-FMVA53A3W:/home$ cd
fukamatiken@fukamatiken-FMVA53A3W:$ ls
Applications  Downloads  Public     backup              snap
Desktop       Music      Templates  bws02@10.252.0.102  wireshark
Documents     Pictures   Videos     qemu-scripts        ダウンロード
fukamatiken@fukamatiken-FMVA53A3W:$ ./
bash: ./: ディレクトリです
fukamatiken@fukamatiken-FMVA53A3W:$

**Comment by totto2727** [comment]
```bash
fukamatiken@fukamatiken-FMVA53A3W:$ ls
Applications Downloads Public backup snap
Desktop Music Templates bws02@10.252.0.102 wireshark
Documents Pictures Videos `qemu-scripts` ダウンロード
```

ここに入らないとダメだよー
確かチュートリアルに含めてたような気がする

```bash
cd
git clone https://github.com/infra-club-fmlorg/qemu-scripts.git
cd qemu-scripts
```

**Comment by kaitokuroda** [comment]
うまくいきました。ありがとうございます。
